### ISSUE TITLE
Error EleUnpack

### ISSUE THREAD

**Issue by wilfriedp** [LuaxY/PyDofus#4] opened 2016-04-26 17:21 UTC
Bonjour, j'ai actuellement un problème avec le ele_unpacker, il m'affiche ceci : 
Traceback (most recent call last):
  File "C:\Users\wilfried\Desktop\PyDofus-master\ele_unpack.py", line 7, in <module>
    file = sys.argv[1]
IndexError: list index out of range

J'ai bien le fichier ele dans le input.

**Comment by LuaxY** [comment] 2016-04-26 19:13
```
$ python ele_unpack.py elements.ele
# file output: elements.json
```

**Comment by balciseri** [comment] 2016-04-26 19:23
http://puu.sh/o3clC/657ce8bea7.png I also get an error

**Comment by LuaxY** [comment] 2016-04-26 19:31
Dofus client version ?
Is elements.ele in the same folder as ele_unpack.py ?
Are you using Python 3 ?

**Comment by balciseri** [comment] 2016-04-26 19:41
That error was from 25days ago on commit day.
I just updated to last version now, still same error.
Yes elements.ele is in the same folder as ele_unpack.py.
I'm using Python 2.7.3. I bet this is the cause right?

**Comment by LuaxY** [comment] 2016-04-26 19:43
"Python 3 scripts to pack/unpack Dofus files"
The second line of README.

**Comment by balciseri** [comment] 2016-04-26 19:44
I missed it ;)
I think because everything else worked fine.
You can close the issue!

**Comment by wilfriedp** [comment] 2016-04-27 09:37
Woups ! My bad, i use python 3.5, but my command is ele_unpack.py elements.ele because "python" dosent exist, and the real command is py ele_unpack.py elements.ele

Now it's worked, sorry.

**Closed as completed** 2016-04-27 09:37 UTC
